import React, { useState, useEffect } from 'react';
import { Modal, Form, Input, Button, Select, message, Spin, Radio, Tooltip } from 'antd';
import { LinkOutlined, InfoCircleOutlined } from '@ant-design/icons';
import { useDatabase, FeedSource, Group } from '../contexts/DatabaseContext';

interface AddFeedModalProps {
  visible: boolean;
  onOk: (feed: FeedSource) => void;
  onCancel: () => void;
  groups: Group[];
}

const AddFeedModal: React.FC<AddFeedModalProps> = ({ visible, onOk, onCancel, groups }) => {
  const [form] = Form.useForm();
  const { db } = useDatabase();
  const [loading, setLoading] = useState(false);
  const [feedInfo, setFeedInfo] = useState<{ title: string; url: string } | null>(null);

  useEffect(() => {
    if (!visible) {
      form.resetFields();
      setFeedInfo(null);
      setLoading(false);
    }
  }, [visible, form]);

  const handleFetchInfo = async () => {
    const url = form.getFieldValue('url');
    if (!url || !url.startsWith('http')) {
      message.error('请输入一个有效的 URL');
      return;
    }
    setLoading(true);
    try {
      const parsedFeed = await window.electron.parseRssFeed(url);
      if (parsedFeed && parsedFeed.title) {
        setFeedInfo({ title: parsedFeed.title, url });
        form.setFieldsValue({
          title: parsedFeed.title,
        });
      } else {
        message.error('无法解析此链接，请确认它是一个有效的 RSS/Atom/JSON Feed');
        setFeedInfo(null);
      }
    } catch (error: any) {
      message.error(`解析失败: ${error.message}`);
      setFeedInfo(null);
    } finally {
      setLoading(false);
    }
  };

  const handleOk = async () => {
    try {
      const values = await form.validateFields();
      const newFeed: FeedSource = {
        // id will be generated by Dexie
        title: values.title,
        url: values.url,
        groupId: values.groupId || undefined,
        updateFrequency: 3600, // 默认1小时
        lastUpdated: new Date(0), // 立即刷新
        unreadCount: 0,
        active: true,
        bionicReading: false,
        viewMode: 'full', // 旧字段，保留默认值
        defaultViewMode: values.defaultViewMode, // 新增字段
      };

      if (db) {
        const id = await db.feeds.add(newFeed);
        onOk({ ...newFeed, id: id as string });
        form.resetFields();
      }
    } catch (error) {
      console.error('Failed to add feed:', error);
    }
  };

  return (
    <Modal
      title="添加订阅源"
      visible={visible}
      onOk={handleOk}
      onCancel={onCancel}
      confirmLoading={loading}
    >
      <Spin spinning={loading} tip="正在解析链接...">
        <Form form={form} layout="vertical" name="add_feed_form">
          <Form.Item
            name="url"
            label="订阅源链接"
            rules={[{ required: true, message: '请输入订阅源链接' }]}
          >
            <Input.Search
              placeholder="https://example.com/feed.xml"
              enterButton="解析"
              onSearch={handleFetchInfo}
            />
          </Form.Item>

          {feedInfo && (
            <>
              <Form.Item
                name="title"
                label="标题"
                rules={[{ required: true, message: '请输入标题' }]}
              >
                <Input />
              </Form.Item>

              <Form.Item name="groupId" label="添加到分组">
                <Select placeholder="不选择则为根目录">
                  {groups.map((g) => (
                    <Select.Option key={g.id} value={g.id}>
                      {g.name}
                    </Select.Option>
                  ))}
                </Select>
              </Form.Item>

              <Form.Item 
                name="defaultViewMode" 
                label={
                  <span>
                    默认阅读模式&nbsp;
                    <Tooltip title="摘要模式只显示Feed提供的简介，全文模式会尝试抓取原文所有内容。此项可在之后编辑。">
                      <InfoCircleOutlined />
                    </Tooltip>
                  </span>
                }
                initialValue="summary"
              >
                <Radio.Group>
                  <Radio.Button value="summary">摘要</Radio.Button>
                  <Radio.Button value="fulltext">全文</Radio.Button>
                </Radio.Group>
              </Form.Item>
            </>
          )}
        </Form>
      </Spin>
    </Modal>
  );
};

export default AddFeedModal; 